name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: lint check
      run: | 
        go get -u golang.org/x/lint/golint \
            github.com/kisielk/errcheck \
            github.com/opennota/check/cmd/aligncheck \
            github.com/opennota/check/cmd/structcheck \
            github.com/opennota/check/cmd/varcheck \
            honnef.co/go/tools/cmd/staticcheck 
        go mod download
        GOFMT_RESULT=`go fmt ./...`; echo $GOFMT_RESULT; test -z "$GOFMT_RESULT"
        go vet ./...
        golint -set_exit_status ./...
        staticcheck -checks SA4006 ./...
        GOOS=linux go build -a -installsuffix cgo -o kaspad .
    - name: test
      run: go test ./...





>>>>>>> issue#1120
